### PR TITLE
Thermostat Beta Update

### PR DESCRIPTION
**Pull request by carTloyal123**
Updated Thermostat implementation that had some broken merge conflicts in it.

### CODE REVIEW

**Comment by carTloyal123** [comment]
@jfarmer08 this should be a good beta version to merge.

**Comment by jfarmer08** [comment]
Not trying to be a pain, but your branch is base on the rebase. Since there are so many changes in that and it's more of a playground at this point could you make a copy of what you have and then pull my dev branch down. From there create a branch from it. So when you do a pull request we only see the changes you have for the thermostat. If that does not makes sense let me know.

**Comment by jfarmer08** [comment]
I don't mind doing it, but I would like to give you credit for this.

**Comment by carTloyal123** [comment]
Ah I see, yeah I had merged it all a little chaotic and it did not come out correctly. I will have it up tomorrow then.

**Comment by carTloyal123** [comment]
@jfarmer08 things should be good to go now, let me know if there is still an issue!

**Comment by jfarmer08** [comment]
Looks good. I will merge this tonight

**Pull request merged**
